<table>
    <thead>
        <tr>
            <th>Currency:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>Start Date:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>End Date:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>Showing:</th>
            <td>data</td>
        </tr>
    </thead>
</table>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Deposits</th>
            <th>Withdrawals</th>
            <th>Balance</th>
        </tr>
    </thead>
    <tbody>
    @foreach($paymentOptionExports as $paymentOptionExport)
        <tr>
            <td>{{$paymentOptionExport['name']}}</td>
            <td>{{$paymentOptionExport['deposit']}}</td>
            <td>{{$paymentOptionExport['withdrawals']}}</td>
            <td>{{$paymentOptionExport['balance']}}</td>
        </tr>
        @endforeach
    </tbody>
</table>