<table>
    <thead>
        <tr>
            <th>Currency:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>Start Date:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>End Date:</th>
            <td>data</td>
        </tr>
    </thead>
</table>
<table>
    <thead>
        <tr>
            <th>Profit Report (before tax):</th>
        </tr>
        <tr>
            <th>Sales</th>
            <td>{{@$overViewExports['Sales']}}</td>
        </tr>
        <tr>
            <th>Expenses</th>
            <td>{{@$overViewExports['Expenses']}}</td>
        </tr>
        <tr>
            <th>Profit</th>
            <td>{{@$overViewExports['Profit']}}</td>
        </tr>

    </thead>
</table>
<table>
    <thead>
        <tr>
            <th>Sales Report:</th>
        </tr>
        <tr>
            <th>Invoiced</th>
            <td>{{@$overViewExports['Invoiced']}}</td>
        </tr>
        <tr>
            <th>Paid</th>
            <td>{{@$overViewExports['Paid']}}</td>
        </tr>
        <tr>
            <th>Unpaid</th>
            <td>{{@$overViewExports['Unpaid']}}</td>
        </tr>
    </thead>
</table>
<table>
    <thead>
        <tr>
             <th>Purchasing Report:</th>
        </tr>
        <tr>
            <th>Invoiced</th>
            <td>{{@$overViewExports['PInvoiced']}}</td>
        </tr>
        <tr>
            <th>Paid</th>
            <td>{{@$overViewExports['PPaid']}}</td>
        </tr>
        <tr>
            <th>Unpaid</th>
            <td>{{@$overViewExports['PUnpaid']}}</td>
        </tr>
    </thead>
</table>