<table>
    <thead>
        <tr>
            <th>Currency:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>After tax:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>Start Date:</th>
            <td>data</td>
        </tr>
        <tr>
            <th>End Date:</th>
            <td>data</td>
        </tr>
    </thead>
</table>
<table>
    <thead>
        <tr>
            <th>Estimates by State:</th>
        </tr>
        <tr>
            <th>State</th>
            <th>Quantity</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>pending</td>
            <td>30</td>
            <td>40</td>
        </tr>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <th>Orders by State:</th>
        </tr>
        <tr>
            <th>State</th>
            <th>Quantity</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>pending</td>
            <td>30</td>
            <td>40</td>
        </tr>
    </tbody>
</table>
<table>
    <thead>
        <tr>
            <th>Delivery Notes by State:</th>
        </tr>
        <tr>
            <th>State</th>
            <th>Quantity</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>pending</td>
            <td>30</td>
            <td>40</td>
        </tr>
    </tbody>
</table>